In [ ]:
pip install torch


In [6]:
import torch


In [29]:
x=torch.arange(12)
x
x.shape
x.reshape(-1,4)
x.reshape(4,-1)
x.size()
torch.tensor([[2,1,4,3],[1,2,3,4],[1,4,3,2]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [1, 4, 3, 2]])

In [27]:
x=torch.tensor([1.0,2,3,8])
y=torch.tensor([2,2,2,2])
x + y,x - y,x*y,x/y,x**y

(tensor([ 3.,  4.,  5., 10.]),
 tensor([-1.,  0.,  1.,  6.]),
 tensor([ 2.,  4.,  6., 16.]),
 tensor([0.5000, 1.0000, 1.5000, 4.0000]),
 tensor([ 1.,  4.,  9., 64.]))

In [28]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 2.0086e+01, 2.9810e+03])

In [37]:
x=torch.arange(12,dtype=torch.float32).reshape((-1,4))
x



tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [38]:
y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [39]:
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [40]:
x==y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [42]:
x.sum()

tensor(66.)

In [47]:
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [48]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])