In [72]:
pip install torch

Note: you may need to restart the kernel to use updated packages.


In [4]:
import torch


In [5]:
x=torch.arange(12)
x
x.shape
x.reshape(-1,4)
x.reshape(4,-1)
x.size()
torch.tensor([[2,1,4,3],[1,2,3,4],[1,4,3,2]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [1, 4, 3, 2]])

In [6]:
x=torch.tensor([1.0,2,3,8])
y=torch.tensor([2,2,2,2])
x + y,x - y,x*y,x/y,x**y

(tensor([ 3.,  4.,  5., 10.]),
 tensor([-1.,  0.,  1.,  6.]),
 tensor([ 2.,  4.,  6., 16.]),
 tensor([0.5000, 1.0000, 1.5000, 4.0000]),
 tensor([ 1.,  4.,  9., 64.]))

In [7]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 2.0086e+01, 2.9810e+03])

In [8]:
x=torch.arange(12,dtype=torch.float32).reshape((-1,4))
x



tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [9]:
y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [10]:
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [11]:
x==y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [69]:
# 课后习题
x>y

tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])

In [70]:
# 课后习题
x<y

tensor([[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]])

In [12]:
x.sum()

tensor(66.)

In [13]:
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [14]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

**2.1.4 切片和索引**

In [34]:
import torch
x=torch.arange(12)

x.reshape(-1,4)
x[-1]

tensor(11)

*左闭右开*

In [41]:
x[1:2]=9
x=x.reshape(-1,3)
x

tensor([[ 0,  9,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [43]:
x[0:2, :] = 12
x

tensor([[12, 12, 12],
        [12, 12, 12],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [46]:
y=y.reshape(-1,3)
after=id(y)
y=x+y
id(y)==after


False

**使用切片索引法直接替换原数据可以节省内存**

In [60]:
original_list = [0, 1, 2, 3, 4]

# 正确做法：直接切片赋值，原地修改
original_list[1:4] = [99]  # 直接覆盖原列表的切片区域
print(original_list)               # 输出 [0, 99, 99, 99, 4]

[0, 99, 4]


**大数量使用切片法可直接用乘**

In [61]:
original_list = [0, 1, 2, 3, 4]

# 正确做法：直接切片赋值，原地修改
original_list[1:4] = [99]*3 # 直接覆盖原列表的切片区域
print(original_list) 

[0, 99, 99, 99, 4]


In [65]:
before = id(x)
x[:]=x+y
id(x)==before

True

In [79]:
# 课后作业
# 创建一个三维张量
c=torch.arange(12).reshape(2,2,3)
d=torch.arange(12).reshape(2,1,6)


********数据预处理********

*读取数据集*

In [1]:
import os
os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file=os.path.join('..','data','house_tiny.csv')
with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n')#列名
    f.write('NA,pave,127500\n')#每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [2]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


*处理缺失值*

In [10]:
# 插值法
inputs,outputs=data.iloc[:,0],data.iloc[:,2]
inputs=inputs.fillna(inputs.mean())
print(inputs)

0    3.0
1    2.0
2    4.0
3    3.0
Name: NumRooms, dtype: float64
